# Generated by Django 4.1.7 on 2023-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=5)),
                ('email_id', models.EmailField(max_length=254)),
                ('company_code', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('website', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
